# Dockerfile
#
# This file defines the steps to build a production-ready container
# for your Vite/React application. It uses a multi-stage build to keep
# the final image small and secure.

# --- Stage 1: Build Environment ---
# We use a Node.js image to install dependencies and build the application.
# Using a specific, recent version of the -alpine image mitigates known vulnerabilities.
FROM node:20-alpine3.19 AS builder

# Set the working directory inside the container.
WORKDIR /src

# Copy the package.json and lock file to leverage Docker's build cache.
# This step is only re-run if these files change.
COPY package*.json ./

# Install project dependencies.
# Replace 'npm install' with 'yarn install' or 'pnpm install' if you use them.
RUN npm install

# Copy the rest of the application source code into the container.
COPY . .

# Build the application for production.
# This command should match the script in your package.json.
RUN npm run build


# --- Stage 2: Production Environment ---
# We use a lightweight Nginx web server to serve the static files
# generated by the build process. This is efficient and secure.
FROM nginx:1.25-alpine3.19

# Copy our custom Nginx configuration file into the container.
# This will overwrite the default Nginx config to listen on the correct port.
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built static files from the 'builder' stage into Nginx's public HTML directory.
COPY --from=builder /src/dist /usr/share/nginx/html

# Expose port 8080, which is standard for many cloud container platforms.
EXPOSE 8080

# The default Nginx command will start the web server automatically
# when the container starts.
CMD ["nginx", "-g", "daemon off;"]
